name: Deploy Updated Image to GKE

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  repository_dispatch:
    types:
      - update-image

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout CDK8s Repository
      - name: Checkout CDK8s Code
        uses: actions/checkout@v3

      # Step 2: Install Google Cloud CLI
      - name: Install Google Cloud CLI
        run: |
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-433.0.0-linux-x86_64.tar.gz
          tar -xzf google-cloud-cli-433.0.0-linux-x86_64.tar.gz
          ./google-cloud-sdk/install.sh -q
          ./google-cloud-sdk/bin/gcloud components install gke-gcloud-auth-plugin
          ./google-cloud-sdk/bin/gcloud components update --quiet
          echo "PATH=$PATH:$(pwd)/google-cloud-sdk/bin" >> $GITHUB_ENV

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Installing Kubectl
        run: |
          gcloud components install kubectl

      # Step 3: Configure kubectl for GKE
      - name: Configure kubectl with GKE Credentials
        run: |
          gcloud container clusters get-credentials tt-us-central1 --region us-central1 --project stefan-work 
          kubectl config set-credentials gke-user --auth-provider=external

      # Step 4: Set Up Node.js for CDK8s
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 5: Install CDK8s CLI
      - name: Install CDK8s CLI
        run: npm install -g cdk8s-cli

      - name: Maven Build
        run: mvn clean compile

      # Step 6: Generate Kubernetes Manifests with CDK8s
      - name: Synthesize CDK8s Manifests
        run: |
          cdk8s synth

      - name: List Generated Manifests
        run: ls -la dist/

      # Step 7: Apply Kubernetes Manifests to GKE
      - name: Deploy to GKE
        run: kubectl apply -f dist/