name: Deploy Updated Image to GKE

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update-image

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout CDK8s Repository
      - name: Checkout CDK8s Code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Configure kubectl for GKE
      - name: Configure kubectl with GKE Credentials
        run: |
          gcloud container clusters get-credentials tt-us-central1 --region us-central1 --project stefan-work 
          kubectl config current-context

      # Step 4: Set Up Node.js for CDK8s
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Gcloud Components
        run: |
          gcloud components install kubectl

      # Step 5: Install CDK8s CLI
      - name: Install CDK8s CLI
        run: npm install -g cdk8s-cli

      - name: Maven Build
        run: mvn clean compile

      # Step 6: Generate Kubernetes Manifests with CDK8s
      - name: Synthesize CDK8s Manifests
        run: |
          cdk8s synth

      - name: List Generated Manifests
        run: ls -la dist/

      # Step 7: Apply Kubernetes Manifests to GKE
      - name: Deploy to GKE
        run: kubectl apply -f dist/